//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Bank
    {
        public int Id { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<int> IdBank { get; set; }
        public string Bik { get; set; }
        public string KorAccount { get; set; }
        public string Inn { get; set; }
        public string Kpp { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
