//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Equipment
    {
        public int Id { get; set; }
        public Nullable<int> IdEquipment { get; set; }
        public Nullable<int> IdEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
