//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.HistoryCountMaterial = new HashSet<HistoryCountMaterial>();
            this.Inventory = new HashSet<Inventory>();
            this.Production = new HashSet<Production>();
            this.SupplyMaterial = new HashSet<SupplyMaterial>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdMaterialType { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountInPack { get; set; }
        public Nullable<int> IdMeasure { get; set; }
        public Nullable<int> CountInStorage { get; set; }
        public Nullable<int> MinCount { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryCountMaterial> HistoryCountMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual MeasureType MeasureType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyMaterial> SupplyMaterial { get; set; }
    }
}
