//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grid
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoEntities4 : DbContext
    {
        public DemoEntities4()
            : base("name=DemoEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent_PontOfSales> Agent_PontOfSales { get; set; }
        public virtual DbSet<AgentType> AgentType { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Employee_Bank> Employee_Bank { get; set; }
        public virtual DbSet<Employee_Equipment> Employee_Equipment { get; set; }
        public virtual DbSet<EmployeeType> EmployeeType { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<HistoryAgentSales> HistoryAgentSales { get; set; }
        public virtual DbSet<HistoryCountMaterial> HistoryCountMaterial { get; set; }
        public virtual DbSet<HistoryMinCostProductForAgent> HistoryMinCostProductForAgent { get; set; }
        public virtual DbSet<HistorySupplyMaterial> HistorySupplyMaterial { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<MeasureType> MeasureType { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<PointOfSales> PointOfSales { get; set; }
        public virtual DbSet<PriorityType> PriorityType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Request_Product> Request_Product { get; set; }
        public virtual DbSet<RequestStageType> RequestStageType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierType> SupplierType { get; set; }
        public virtual DbSet<SupplyMaterial> SupplyMaterial { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Turnstile> Turnstile { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
