//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Production = new HashSet<Production>();
            this.Request_Product = new HashSet<Request_Product>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdAgent { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IdRequestProduct { get; set; }
        public Nullable<int> IdRequestStage { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public Nullable<System.DateTime> DateOfRequest { get; set; }
        public Nullable<bool> IsDelivery { get; set; }
        public Nullable<int> IdManager { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Product> Request_Product { get; set; }
        public virtual RequestStageType RequestStageType { get; set; }
    }
}
