//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grid
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplyMaterial()
        {
            this.HistorySupplyMaterial = new HashSet<HistorySupplyMaterial>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> IsDelivery { get; set; }
        public Nullable<int> IdEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorySupplyMaterial> HistorySupplyMaterial { get; set; }
        public virtual Material Material { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
