//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnstile
    {
        public int Id { get; set; }
        public Nullable<int> IdCard { get; set; }
        public Nullable<System.DateTime> DateTimeArrivel { get; set; }
        public Nullable<System.DateTime> DateTimeDeparture { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
